on:
  workflow_dispatch:

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Check deprecated function
        run: |
          deprecated=true
          if [[ deprecated ]]; then
            echo "::warning::Deprecated function found"
          fi
